Header
llmex/project-fullstack-team pull request #14
Opened 2024-04-13 07:52 UTC by MAKSYM77Ogi

2024-04-13 10:13 UTC, llmex requested changes
Клас ".header-container" в тебе нічого не орби , тільки заважає - він зайвий, його треба удалити. 
Потім у класі ".header-icon" властивість "flex-direction: row" теж зайва, бо вона йде за замовчуванням. 

У класі ".icon" ще треба поставити "margin-left: auto", щоб відштовхнути бургер вправо. 

У класі ".wrap-nav-button" властивість "margin-left: auto" зайва, тільки заважає та не дає правильно розміститися іконкам у хедері.

Класу "icon" треба додати "margin-left: auto;" для того, щоб штовхнути його у край. 

У класі ".page-link" "margin: 0" та "padding: 0" та "list-style: none" зайві, бо вони прописані у файлі "reset.css". 

Класу ".wrap-nav-button" потрібно прописати "gap: 20px" - це задасть відстань між навігацією та кнопкою. 

Відстань між елементами списку - тобто елементам із класом "page-link-link" ( його можна переназвати "page-link-list" ) не 20рх, вона там 8рх. 
Цю маніпуляцію з дістанцією можна виконати за допомогою такого класу : 
".page-link-link:not(:last-child) {
          margin-right: 8px;
 }*

Тоді класи ".page-link li:last-child" та ".page-link li" будуть зайві. 


У медіазапиті на 375рх треба задати контейнеру "paddding-left" "padding-right" по 20рх.

У медіазапиті на 768рх теж треба задати контейнеру "paddding-left" "padding-right" по 32рх. Та змінити ширину на просто "width" , а не "max-width" - бо це робить обмеження у ширині на десктопі. 

У медіазапиті "max-width: 1280px" зайва властивість "font-family". 

В клас ".main-btn"  треба добавити властивості "font-weight: 600; font-size: 18px; line-height: 1.11; letter-spacing: -0.01em; text-transform: uppercase" "border: none".

У класі ".page-link-link" треба замінити "padding" на "padding-top" та "paddint-bottom" по 12рх. Також не вірно задане значення "width" - воно має бути 114рх.
Властивості "display" , "align-items" " justify-content" "flex-direction" "gap" - зайві, вони не потрібні. Замість них потрібно прописати " text-align: center".
Також у цей же клас треба добавити властивості "font-size: 16px; line-height: 1.25; letter-spacing: -0.02em;"

2024-04-13 12:05 UTC, MAKSYM77Ogi commented
Зроблено . провіряй. Бо я не бачу як воно виглядає на цілому сайті.

2024-04-13 19:19 UTC, llmex requested changes
Клас ".header-container" взагалі не нужен - він усе ломає. Удали його та в тебе усе буде нормально із хедером у мобільці та планшеті. 

Класи ".page-link li" та ".page-link li:last-child" зайві - їх теж треба удалити. 

Для кнопки у класі ".main-btn" постав "padding: 16px" та добав "border: none"

2024-04-14 13:34 UTC, llmex requested changes
Помітив деякі речі, які треба змінити : у css удалити зовсім клас ".header-container". 

Змінити атрибут у посиланнях на "href=#works" , "href=#veg", "href=#reviews". 

Та ще потрібно кожній лішці, тобто елементу з класом "page-link-list" задати свою ширину. Подивись на макеті , вони там мають кожна різні розміри . 
Перша - 114рх, Друга - 101рх, Третя  - 81рх. Треба це зробити за допомогою додаткового класу для кожної з них

2024-04-15 11:48 UTC, llmex approved these changes

2024-04-15 11:48 UTC, merged